model:
    transformer:
        name: 'transformer'
        d_model: 512
        nhead: 8
        n_encoder_layer: 2 # number of encoder layer
        n_decoder_layer: 1 # number of decoder layer
        dim_feedforward: 2048 # dimension of hidden layer of FF in transformer
        drop: 0 # dropout ratio
        batch_first: true # to pass into enocder layer module
        embedding_dim: 20 # embedding dimension of agent IDs
        in_mlp_layers: [56, 128, 256, 512] # input side MLP
        out_mlp_layers: [512, 128, 56] # output side MLP
        embed_before_mlp: true # check for using agent embedding before input side MLP
        only_encoder: true # check for using only encoder of transformer
        dynamic_mask: true # check for using ball2vec++ mask(i.e., true) against ball2vec mask(i.e., false)

train:
    epochs: 10 # no. of epochs
    batch_size: 64 
    lr: 0.001 # initial learning rate 
    num_workers: 0 
    use_agent_id: true # check for using agent ID
    use_pos_embedding: true # check for using position embedding
    weight_folder: 'weights' # name of folder of stored parameters of model
    save_model: True # check for saving model parameters
    save_step: 2 # no. of epochs to skip for saving model
    # preload: 'latest' # either "latest" or specifie the epoch
    skip_validation: false # check for validation step: false for validation
    val_step: 2 # no. of epochs to skip for validation step
data:
    directory: 'data'
    charge:
        name: 'charge'
        n_particles: 5 # no. of agents
        name_format: '{data}_{mode}_charged{n}.npy' # synthetic data file name format
        encoder_ratio: 0.5
        test_encoder_ratio: 0.6
        
        
